### ISSUE TITLE
Shortcuts to installing Linux upgrades

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/docs.rancherdesktop.io#176]
There should be some quick link on https://docs.rancherdesktop.io/getting-started/installation/#linux for users just wanting to upgrade to the latest version.

For Windows and macOS the users just download the latest version directly from the Github release page, but for Linux they have to read through several blocks of text to find the relevant information.

**Comment by adamkpickering** [comment]
I disagree. If a user is looking to update Rancher Desktop, in most cases (deb and rpm installs), they just do an update using their package manager, which is 1 or 2 commands.

If they are using the AppImage, they've already been through the installation process and know that the steps immediately under https://docs.rancherdesktop.io/getting-started/installation/#linux don't need to be done again. We could make the AppImage update process easier (it could work like it does on Windows and macOS), but other things have been more important.

I think one thing could make it clearer though. Instead of "Requirements", "Ensuring You Have Access to `/dev/kvm`", "`pass` Setup" and "Traefik Port Binding Access" being the same level of heading as "Installation via .deb Package" and the other installation/uninstallation steps, I would put them as one level lower. That would make it easier for users to jump right to the installation steps, even though it would cause issues for some users.
