### ISSUE TITLE
Move Troubleshooting to bottom as a top-level menu under FAQ 

### ISSUE THREAD

**Issue by gaktive** [rancher-sandbox/docs.rancherdesktop.io#75]
We should move https://docs.rancherdesktop.io/getting-started/features#troubleshooting-tips away from under Features and have it be its own top-level menu item in the Docs. Preferably at the bottom under FAQ. Then we can update Rancher Desktop with a link to that section, which we can expand over time.

**Comment by btat** [comment]
All the top-level headers on https://docs.rancherdesktop.io/getting-started/features/ currently correspond to the menu/navigation items on RD itself, with the exception of the docs using "Troubleshooting Tips" instead of "Troubleshooting".

Would it make sense to add a new "Troubleshooting Tips" under FAQ and update the header label on  https://docs.rancherdesktop.io/getting-started/features/ instead of moving the section out?

**Comment by jandubois** [comment]
> Would it make sense to add a new "Troubleshooting Tips" under FAQ and update the header label on https://docs.rancherdesktop.io/getting-started/features/ instead of moving the section out?

Yes, I think so. The entry under "Features" just documents the app interface, but the top level "Troubleshooting Tips" would provide workarounds to common problems.

I want the latter to be immediately visible when you look at the docs; you should not have to search for them. That's why they need to be a top-level entry.

**Comment by gunamata** [comment]
@jandubois , Do you have any items/topics in mind that we can add under the new `Troubleshooting Tips` section?
